version: "3.9"

services:
######## PRODUCTION ########
  quote-price-redis:
    build: 
      context: ./timo-redis-docker/
      dockerfile: redis_dockerfile
    ports:
      - "6379" # Redis port, only exposed internally
    healthcheck:
      test: redis-cli -a timo-daytrade-redispass-8166d5d6-d622-4b62-bfdd-8c7d1a154c2f ping | grep PONG
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 15s
    profiles:
      - production

  trigger-symbol-redis:
    build: 
      context: ./timo-redis-docker/
      dockerfile: redis_dockerfile
    ports:
      - "6379" # Redis port, only exposed internally
    healthcheck:
      test: redis-cli -a timo-daytrade-redispass-8166d5d6-d622-4b62-bfdd-8c7d1a154c2f ping | grep PONG
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 15s
    profiles:
      - production

  rabbitmq:
    build: 
      context: ./timo-rabbitmq-docker/
      dockerfile: rabbitmq_dockerfile
    ports:
      - "5672"
      - "15672"
    healthcheck:
      test: rabbitmq-diagnostics -q check_running | grep "fully booted and running"
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 15s
    profiles:
      - production

  quote-driver:
    build: 
      context: . # In order to be able to access files in the "timo-quote-driver-source" directory we have to move the context up one directory
      dockerfile: ./timo-quote-driver-docker/quote_driver_dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      quote-price-redis:
        condition: service_healthy
    profiles:
      - production

  trigger-driver:
    build: 
      context: . # In order to be able to access files in the "timo-trigger-driver-source" directory we have to move the context up one directory
      dockerfile: ./timo-trigger-driver-docker/trigger_driver_dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      trigger-symbol-redis:
        condition: service_healthy
    profiles:
      - production

  stock-watcher:
    build: 
      context: . # In order to be able to access files in the "timo-trigger-driver-source" directory we have to move the context up one directory
      dockerfile: ./timo-stock-watcher-docker/stock_watcher_dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      trigger-symbol-redis:
        condition: service_healthy
    profiles:
      - production
    
  web-interface:
    build:
      context: ./timo-web-interface/
      dockerfile: web_dockerfile
    ports:
      - 80:80
    profiles:
      - production


######## DEVELOPMENT ########
  mongodb-dev:
    container_name: "mongodb"
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 15s
    profiles:
      - dev

  quote-price-redis-dev:
    container_name: "quote-price-redis"
    build: 
      context: ./timo-redis-docker/
      dockerfile: redis_dev_dockerfile
    ports:
      - "6379:6379" # Redis port, exposed internally and externally
      - "8001:8001" # Redis Insight Port, exposed internally and externally
    healthcheck:
      test: redis-cli -a timo-daytrade-redispass-8166d5d6-d622-4b62-bfdd-8c7d1a154c2f ping | grep PONG
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 15s
    profiles:
      - dev

  trigger-symbol-redis-dev:
    container_name: "trigger-symbol-redis"
    build: 
      context: ./timo-redis-docker/
      dockerfile: redis_dev_dockerfile
    ports:
      - "6380:6379" # Redis port, exposed internally and externally
      - "8002:8001" # Redis Insight Port, exposed internally and externally
    healthcheck:
      test: redis-cli -a timo-daytrade-redispass-8166d5d6-d622-4b62-bfdd-8c7d1a154c2f ping | grep PONG
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 15s
    profiles:
      - dev
  
  rabbitmq-dev:
    container_name: "rabbitmq"
    build: 
      context: ./timo-rabbitmq-docker/
      dockerfile: rabbitmq_dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q check_running | grep "fully booted and running"
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 15s
    profiles:
      - dev

  quote-driver-dev:
    build: 
      context: . # In order to be able to access files in the "timo-quote-driver-source" directory we have to move the context up one directory
      dockerfile: ./timo-quote-driver-docker/quote_driver_dockerfile
    depends_on:
      rabbitmq-dev:
        condition: service_healthy
      quote-price-redis-dev:
        condition: service_healthy
    profiles:
      - dev

  trigger-driver-dev:
    build: 
      context: . # In order to be able to access files in the "timo-trigger-driver-source" directory we have to move the context up one directory
      dockerfile: ./timo-trigger-driver-docker/trigger_driver_dockerfile
    depends_on:
      rabbitmq-dev:
        condition: service_healthy
      trigger-symbol-redis-dev:
        condition: service_healthy
    profiles:
      - dev

  stock-watcher-dev:
    build: 
      context: . # In order to be able to access files in the "timo-trigger-driver-source" directory we have to move the context up one directory
      dockerfile: ./timo-stock-watcher-docker/stock_watcher_dockerfile
    depends_on:
      rabbitmq-dev:
        condition: service_healthy
      trigger-symbol-redis-dev:
        condition: service_healthy
    profiles:
      - dev
      
  web-interface-dev:
    build:
      context: ./timo-web-interface/
      dockerfile: web_dockerfile
    ports:
      - 80:80
    profiles:
      - dev

  transaction-server-dev:
    build:
      context: .
      dockerfile: ./timo-transaction-server-docker/transaction_server_dockerfile
    depends_on:
      mongodb-dev:
        condition: service_healthy
      rabbitmq-dev:
        condition: service_healthy
    profiles:
      - dev