version: "3.9"

services:
######## PRODUCTION ########
  redis:
    build: 
      context: ./timo-redis-docker/
      dockerfile: redis_dockerfile
    ports:
      - "6379" # Redis port, only exposed internally
    profiles:
      - production

  rabbitmq:
    build: 
      context: ./timo-rabbitmq-docker/
      dockerfile: rabbitmq_dockerfile
    ports:
      - "5672"
      - "15672"
    profiles:
      - production

  quote-driver:
    build: 
      context: . # In order to be able to access files in the "timo-quote-driver-source" directory we have to move the context up one directory
      dockerfile: ./timo-quote-driver-docker/quote_driver_dockerfile
    ports:
      - "5672"
    depends_on:
      - rabbitmq
    profiles:
      - production

######## DEVELOPMENT ########
  redis-dev:
    container_name: "redis"
    build: 
      context: ./timo-redis-docker/
      dockerfile: redis_dev_dockerfile
    ports:
      - "6379:6379" # Redis port, exposed internally and externally
      - "8001:8001" # Redis Insight Port, exposed internally and externally
    profiles:
      - dev
  
  rabbitmq-dev:
    container_name: "rabbitmq"
    build: 
      context: ./timo-rabbitmq-docker/
      dockerfile: rabbitmq_dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles:
      - dev

  quote-driver-dev:
    build: 
      context: . # In order to be able to access files in the "timo-quote-driver-source" directory we have to move the context up one directory
      dockerfile: ./timo-quote-driver-docker/quote_driver_dockerfile
    ports:
      - "5672"
    depends_on:
      - rabbitmq-dev
    profiles:
      - dev