// Code generated by xgen. MODIFIED FOR SUITABILITY

package main

// Log ...
type Log LogType

// LogType ...
type LogType struct {
	UserCommand        []UserCommandType        `xml:"userCommand" json:"user_command" bson:"user_command"`
	QuoteServer        []QuoteServerType        `xml:"quoteServer" json:"quote_server" bson:"quote_server"`
	AccountTransaction []AccountTransactionType `xml:"accountTransaction" json:"account_transaction" bson:"account_transaction"`
	SystemEvent        []SystemEventType        `xml:"systemEvent" json:"system_event" bson:"system_event"`
	ErrorEvent         []ErrorEventType         `xml:"errorEvent" json:"error_event" bson:"error_event"`
	DebugEvent         []DebugType              `xml:"debugEvent" json:"debug_event" bson:"debug_event"`
}

// UserCommandType ...
type UserCommandType struct {
	Timestamp      int64   `xml:"timestamp" json:"timestamp" bson:"timestamp"`
	Server         string  `xml:"server" json:"server" bson:"server"`
	TransactionNum int64   `xml:"transactionNum" json:"transaction_num" bson:"transaction_num"`
	Command        string  `xml:"command" json:"command" bson:"command"`
	Username       string  `xml:"username" json:"username" bson:"username"`
	StockSymbol    string  `xml:"stockSymbol" json:"stock_symbol" bson:"stock_symbol"`
	Filename       string  `xml:"filename" json:"filename" bson:"filename"`
	Funds          float64 `xml:"funds" json:"funds" bson:"funds"`
}

// QuoteServerType ...
type QuoteServerType struct {
	Timestamp       int64   `xml:"timestamp" json:"timestamp" bson:"timestamp"`
	Server          string  `xml:"server" json:"server" bson:"server"`
	TransactionNum  int64   `xml:"transactionNum" json:"transaction_num" bson:"transaction_num"`
	Price           float64 `xml:"price" json:"price" bson:"price"`
	StockSymbol     string  `xml:"stockSymbol" json:"stock_symbol" bson:"stock_symbol"`
	Username        string  `xml:"username" json:"username" bson:"username"`
	QuoteServerTime int64   `xml:"quoteServerTime" json:"quote_server_time" bson:"quote_server_time"`
	Cryptokey       string  `xml:"cryptokey" json:"cryptokey" bson:"cryptokey"`
}

// AccountTransactionType ...
type AccountTransactionType struct {
	Timestamp      int64   `xml:"timestamp" json:"timestamp" bson:"timestamp"`
	Server         string  `xml:"server" json:"server" bson:"server"`
	TransactionNum int64   `xml:"transactionNum" json:"transaction_num" bson:"transaction_num"`
	Action         string  `xml:"action" json:"action" bson:"action"`
	Username       string  `xml:"username" json:"username" bson:"username"`
	Funds          float64 `xml:"funds" json:"funds" bson:"funds"`
}

// SystemEventType ...
type SystemEventType struct {
	Timestamp      int64   `xml:"timestamp" json:"timestamp" bson:"timestamp"`
	Server         string  `xml:"server" json:"server" bson:"server"`
	TransactionNum int64   `xml:"transactionNum" json:"transaction_num" bson:"transaction_num"`
	Command        string  `xml:"command" json:"command" bson:"command"`
	Username       string  `xml:"username" json:"username" bson:"username"`
	StockSymbol    string  `xml:"stockSymbol" json:"stock_symbol" bson:"stock_symbol"`
	Filename       string  `xml:"filename" json:"filename" bson:"filename"`
	Funds          float64 `xml:"funds" json:"funds" bson:"funds"`
}

// ErrorEventType ...
type ErrorEventType struct {
	Timestamp      int64   `xml:"timestamp" json:"timestamp" bson:"timestamp"`
	Server         string  `xml:"server" json:"server" bson:"server"`
	TransactionNum int64   `xml:"transactionNum" json:"transaction_num" bson:"transaction_num"`
	Command        string  `xml:"command" json:"command" bson:"command"`
	Username       string  `xml:"username" json:"username" bson:"username"`
	StockSymbol    string  `xml:"stockSymbol" json:"stock_symbol" bson:"stock_symbol"`
	Filename       string  `xml:"filename" json:"filename" bson:"filename"`
	Funds          float64 `xml:"funds" json:"funds" bson:"funds"`
	ErrorMessage   string  `xml:"errorMessage" json:"error_message" bson:"error_message"`
}

// DebugType ...
type DebugType struct {
	Timestamp      int64   `xml:"timestamp" json:"timestamp" bson:"timestamp"`
	Server         string  `xml:"server" json:"server" bson:"server"`
	TransactionNum int64   `xml:"transactionNum" json:"transaction_num" bson:"transaction_num"`
	Command        string  `xml:"command" json:"command" bson:"command"`
	Username       string  `xml:"username" json:"username" bson:"username"`
	StockSymbol    string  `xml:"stockSymbol" json:"stock_symbol" bson:"stock_symbol"`
	Filename       string  `xml:"filename" json:"filename" bson:"filename"`
	Funds          float64 `xml:"funds" json:"funds" bson:"funds"`
	DebugMessage   string  `xml:"debugMessage" json:"debug_message" bson:"debug_message"`
}

// UnixTimeLimits ...
type UnixTimeLimits int64

// StockSymbolType ...
type StockSymbolType string

// CommandType ...
type CommandType string
